# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and test'
          services:
            - docker
          script:
            - zip -r example-$BITBUCKET_BUILD_NUMBER.zip .
            - echo Building the Docker image...
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD docker.io
            - docker build -t $DOCKER_HUB_USER/hello-world:latest .
            - docker push $DOCKER_HUB_USER/hello-world:latest
          artifacts: 
            - example-*.zip
           
    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: "Deployment to Production"
        deployment: production
        script:
          - pipe: microsoft/azure-web-apps-deploy:1.0.0
            variables:
              AZURE_APP_ID: $AZURE_APP_ID
              AZURE_PASSWORD: $AZURE_PASSWORD
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              AZURE_RESOURCE_GROUP: $RESOURCE_GROUP
              AZURE_APP_NAME: $APP_NAME
              ZIP_FILE: 'example-$BITBUCKET_BUILD_NUMBER.zip'
              
